### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by Sushovan861** [bloomberg/blpapi-node#12]
I have installed blpapi (the build was successful and the all the required code under build/release/... were generated),while adding the require('blpapi') in the node application I am always ending up with Module not found error.

Error: The specified module could not be found.
C:\NODE development\myjs\node_modules\blpapi\build\Release\blpapijs.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\NODE development\myjs\node_modules\blpapi\blpapi.j
s:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I am using the v0.10.20 version of the node on a windows 7 machine with Express studio 2012 installed. The problem as shown in the log refers to the blpapi.js line 6 character 14.

var blpapi = require(path.join(__dirname, '/build/Release/blpapijs'));

when I do the console over path.join it actually shows the right place of the generated code.

Please help me in resolving this issue,

**Comment by ericvw** [comment]
#58 should resolve this issue.
