### ISSUE TITLE
Library not loaded: libblpapi3_64.so

### ISSUE THREAD

**Issue by dtaylor7** [bloomberg/blpapi-node#30]
I have installed blpapi (the build was successful) however i am getting an error in blpapijs.node saying it is unable to load libblpapi3_64.so.

OS: OS X Yosemite
Node: v0.10.16
Stack trace:

```
Error: dlopen(/Users/dominictaylor/Sites/bloomberg/node_modules/blpapi/build/Release/blpapijs.node, 1): Library not loaded: libblpapi3_64.so
  Referenced from: /Users/dominictaylor/Sites/bloomberg/node_modules/blpapi/build/Release/blpapijs.node
  Reason: image not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dominictaylor/Sites/bloomberg/node_modules/blpapi/blpapi.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Please help me in resolving this issue,

**Comment by wcallag3** [comment]
what is the LD path?
