### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by kengz** [bloomberg/blpapi-node#62]
I tried a simple `npm install blpapi` and it screamed at me:

```bash

Wahs-MBP:Quiver kengz$ npm install blpapi
-
> blpapi@1.2.0 install /Users/kengz/Google Drive/Quiver/node_modules/blpapi
> node-gyp configure build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/blpapijs/blpapijs.o
clang: error: no such file or directory: 'Drive/Quiver/node_modules/blpapi/deps/blpapi/include-3.8.1.1'
make: *** [Release/obj.target/blpapijs/blpapijs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/kengz/Google Drive/Quiver/node_modules/blpapi
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "blpapi"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! blpapi@1.2.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blpapi@1.2.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the blpapi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls blpapi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kengz/Google Drive/Quiver/npm-debug.log
Wahs-MBP:Quiver kengz$ 

```

Below is the npm debug log:
```bash
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'blpapi' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'blpapi', null ]
5 verbose cache add spec blpapi
6 silly cache add parsed spec { raw: 'blpapi',
6 silly cache add   scope: null,
6 silly cache add   name: 'blpapi',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed blpapi@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'blpapi', range: '*', hasData: false }
11 silly mapToRegistry name blpapi
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/blpapi
15 verbose addNameRange registry:https://registry.npmjs.org/blpapi not in flight; fetching
16 verbose request uri https://registry.npmjs.org/blpapi
17 verbose request no auth needed
18 info attempt registry request try #1 at 1:44:59 PM
19 verbose request id fef6c904e4bf2e19
20 verbose etag "5EKQ8US0IVJ0KRMZ2CQC43CV2"
21 http request GET https://registry.npmjs.org/blpapi
22 http 304 https://registry.npmjs.org/blpapi
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 24 Apr 2015 17:44:59 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Fri, 24 Apr 2015 17:44:59 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"5EKQ8US0IVJ0KRMZ2CQC43CV2"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-atl6231-ATL',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1429897499.434368,VS0,VE53',
23 silly get     vary: 'Accept' } ]
24 verbose etag https://registry.npmjs.org/blpapi from cache
25 verbose get saving blpapi to /Users/kengz/.npm/registry.npmjs.org/blpapi/.cache.json
26 silly addNameRange number 2 { name: 'blpapi', range: '*', hasData: true }
27 silly addNameRange versions [ 'blpapi',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.1.4',
27 silly addNameRange     '0.1.5',
27 silly addNameRange     '0.1.6',
27 silly addNameRange     '0.1.7',
27 silly addNameRange     '0.1.9',
27 silly addNameRange     '0.1.10',
27 silly addNameRange     '0.1.11',
27 silly addNameRange     '0.1.12',
27 silly addNameRange     '0.1.13',
27 silly addNameRange     '0.1.14',
27 silly addNameRange     '0.1.15',
27 silly addNameRange     '1.0.0',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.2.0' ] ]
28 verbose addNamed blpapi@1.2.0
29 silly addNamed semver.valid 1.2.0
30 silly addNamed semver.validRange 1.2.0
31 silly cache afterAdd blpapi@1.2.0
32 verbose afterAdd /Users/kengz/.npm/blpapi/1.2.0/package/package.json not in flight; writing
33 verbose afterAdd /Users/kengz/.npm/blpapi/1.2.0/package/package.json written
34 silly install resolved [ { name: 'blpapi',
34 silly install resolved     version: '1.2.0',
34 silly install resolved     main: './blpapi.js',
34 silly install resolved     description: 'Bloomberg Open API (BLPAPI) binding for node.js',
34 silly install resolved     os: [ 'linux', 'win32', 'darwin' ],
34 silly install resolved     cpu: [ 'x64', 'ia32' ],
34 silly install resolved     scripts: { install: 'node-gyp configure build' },
34 silly install resolved     dependencies: { 'custom-error-generator': '7.0.0' },
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'https://github.com/bloomberg/blpapi-node.git' },
34 silly install resolved     bugs:
34 silly install resolved      { url: 'https://github.com/bloomberg/blpapi-node/issues',
34 silly install resolved        email: 'open-tech@bloomberg.net' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     keywords:
34 silly install resolved      [ 'finance',
34 silly install resolved        'stocks',
34 silly install resolved        'stock',
34 silly install resolved        'quotes',
34 silly install resolved        'tick',
34 silly install resolved        'realtime',
34 silly install resolved        'market' ],
34 silly install resolved     license: 'MIT',
34 silly install resolved     engines: { node: '>=0.6' },
34 silly install resolved     gitHead: '334a2b13dbb3a82a33ff4544a6b81f01defbc535',
34 silly install resolved     homepage: 'https://github.com/bloomberg/blpapi-node',
34 silly install resolved     _id: 'blpapi@1.2.0',
34 silly install resolved     _shasum: '28bb7d2a191ec9eac3092c28e20d81f26c6efd79',
34 silly install resolved     _from: 'blpapi@*',
34 silly install resolved     _npmVersion: '2.7.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'ericvw', email: 'ericvw@gmail.com' },
34 silly install resolved     dist:
34 silly install resolved      { shasum: '28bb7d2a191ec9eac3092c28e20d81f26c6efd79',
34 silly install resolved        tarball: 'http://registry.npmjs.org/blpapi/-/blpapi-1.2.0.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/blpapi/-/blpapi-1.2.0.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install blpapi@1.2.0 into /Users/kengz/Google Drive/Quiver
36 info installOne blpapi@1.2.0
37 verbose installOne of blpapi to /Users/kengz/Google Drive/Quiver not in flight; installing
38 verbose lock using /Users/kengz/.npm/_locks/blpapi-87077b44487570ec.lock for /Users/kengz/Google Drive/Quiver/node_modules/blpapi
39 silly install write writing blpapi 1.2.0 to /Users/kengz/Google Drive/Quiver/node_modules/blpapi
40 silly cache addNamed cb blpapi@1.2.0
41 verbose unbuild node_modules/blpapi
42 verbose gentlyRm vacuuming /Users/kengz/Google Drive/Quiver/node_modules/blpapi
43 verbose tar unpack /Users/kengz/.npm/blpapi/1.2.0/package.tgz
44 verbose tar unpacking to /Users/kengz/Google Drive/Quiver/node_modules/blpapi
45 verbose gentlyRm vacuuming /Users/kengz/Google Drive/Quiver/node_modules/blpapi
46 silly gunzTarPerm modes [ '755', '644' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm extractEntry README.md
49 silly gunzTarPerm extractEntry LICENSE
50 silly gunzTarPerm extractEntry blpapi.js
51 silly gunzTarPerm extractEntry .travis.yml
52 silly gunzTarPerm extractEntry binding.gyp
53 silly gunzTarPerm extractEntry deps/blpapi/LICENSE
54 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_logging.h
55 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_abstractsession.h
56 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_constant.h
57 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_correlationid.h
58 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_datetime.h
59 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_defs.h
60 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_diagnosticsutil.h
61 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_dispatchtbl.h
62 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_element.h
63 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_error.h
64 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_event.h
65 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_eventdispatcher.h
66 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_eventformatter.h
67 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_exception.h
68 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_identity.h
69 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_call.h
70 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_message.h
71 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_name.h
72 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_providersession.h
73 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_request.h
74 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_resolutionlist.h
75 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_schema.h
76 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_service.h
77 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_session.h
78 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_sessionoptions.h
79 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_streamproxy.h
80 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_subscriptionlist.h
81 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_topic.h
82 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_topiclist.h
83 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_types.h
84 silly gunzTarPerm extractEntry deps/blpapi/include-3.7.9.1/blpapi_versioninfo.h
85 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_message.h
86 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_abstractsession.h
87 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_constant.h
88 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_correlationid.h
89 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_datetime.h
90 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_defs.h
91 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_diagnosticsutil.h
92 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_dispatchtbl.h
93 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_element.h
94 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_error.h
95 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_event.h
96 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_eventdispatcher.h
97 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_eventformatter.h
98 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_exception.h
99 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_highresolutionclock.h
100 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_identity.h
101 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_logging.h
102 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_call.h
103 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_name.h
104 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_providersession.h
105 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_request.h
106 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_resolutionlist.h
107 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_schema.h
108 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_service.h
109 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_session.h
110 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_sessionoptions.h
111 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_streamproxy.h
112 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_subscriptionlist.h
113 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_timepoint.h
114 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_topic.h
115 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_topiclist.h
116 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_types.h
117 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_versioninfo.h
118 silly gunzTarPerm extractEntry deps/blpapi/include-3.8.1.1/blpapi_versionmacros.h
119 silly gunzTarPerm extractEntry deps/blpapi/linux/libblpapi3_32.so
120 silly gunzTarPerm extractEntry deps/blpapi/linux/libblpapi3_64.so
121 silly gunzTarPerm extractEntry deps/blpapi/osx/libblpapi3_32.so
122 silly gunzTarPerm extractEntry deps/blpapi/osx/libblpapi3_64.so
123 silly gunzTarPerm extractEntry deps/blpapi/win/blpapi3_32.lib
124 silly gunzTarPerm extractEntry deps/blpapi/win/blpapi3_64.lib
125 silly gunzTarPerm extractEntry examples/AuthorizationApplication.js
126 silly gunzTarPerm extractEntry examples/FieldSearchRequest.js
127 silly gunzTarPerm extractEntry examples/HistoricalDataRequest.js
128 silly gunzTarPerm extractEntry examples/IntradayBarRequest.js
129 silly gunzTarPerm extractEntry examples/IntradayTickRequest.js
130 silly gunzTarPerm extractEntry examples/Console.js
131 silly gunzTarPerm extractEntry examples/MarketSubUnsubscription.js
132 silly gunzTarPerm extractEntry examples/MarketSubscription.js
133 silly gunzTarPerm extractEntry examples/MarketVwapSubscription.js
134 silly gunzTarPerm extractEntry examples/OptionChain.js
135 silly gunzTarPerm extractEntry examples/MarketBarSubscription.js
136 silly gunzTarPerm extractEntry output.i
137 silly gunzTarPerm extractEntry blpapijs.cpp
138 info preinstall blpapi@1.2.0
139 silly prepareForInstallMany adding custom-error-generator@7.0.0 from blpapi dependencies
140 silly cache add args [ 'custom-error-generator@7.0.0', null ]
141 verbose cache add spec custom-error-generator@7.0.0
142 silly cache add parsed spec { raw: 'custom-error-generator@7.0.0',
142 silly cache add   scope: null,
142 silly cache add   name: 'custom-error-generator',
142 silly cache add   rawSpec: '7.0.0',
142 silly cache add   spec: '7.0.0',
142 silly cache add   type: 'version' }
143 verbose addNamed custom-error-generator@7.0.0
144 silly addNamed semver.valid 7.0.0
145 silly addNamed semver.validRange 7.0.0
146 silly mapToRegistry name custom-error-generator
147 silly mapToRegistry using default registry
148 silly mapToRegistry registry https://registry.npmjs.org/
149 silly mapToRegistry uri https://registry.npmjs.org/custom-error-generator
150 verbose addNameVersion registry:https://registry.npmjs.org/custom-error-generator not in flight; fetching
151 verbose request uri https://registry.npmjs.org/custom-error-generator
152 verbose request no auth needed
153 info attempt registry request try #1 at 1:45:01 PM
154 verbose etag "4Q7QN02P51B0M7JWUZHY1O1AN"
155 http request GET https://registry.npmjs.org/custom-error-generator
156 http 304 https://registry.npmjs.org/custom-error-generator
157 silly get cb [ 304,
157 silly get   { date: 'Fri, 24 Apr 2015 17:45:01 GMT',
157 silly get     via: '1.1 varnish',
157 silly get     'last-modified': 'Fri, 24 Apr 2015 17:45:01 GMT',
157 silly get     'cache-control': 'max-age=60',
157 silly get     etag: '"4Q7QN02P51B0M7JWUZHY1O1AN"',
157 silly get     age: '0',
157 silly get     connection: 'keep-alive',
157 silly get     'x-served-by': 'cache-atl6225-ATL',
157 silly get     'x-cache': 'MISS',
157 silly get     'x-cache-hits': '0',
157 silly get     'x-timer': 'S1429897501.386249,VS0,VE33',
157 silly get     vary: 'Accept' } ]
158 verbose etag https://registry.npmjs.org/custom-error-generator from cache
159 verbose get saving custom-error-generator to /Users/kengz/.npm/registry.npmjs.org/custom-error-generator/.cache.json
160 silly cache afterAdd custom-error-generator@7.0.0
161 verbose afterAdd /Users/kengz/.npm/custom-error-generator/7.0.0/package/package.json not in flight; writing
162 verbose afterAdd /Users/kengz/.npm/custom-error-generator/7.0.0/package/package.json written
163 silly install resolved [ { name: 'custom-error-generator',
163 silly install resolved     version: '7.0.0',
163 silly install resolved     description: 'Custom errors and exceptions in Node.js',
163 silly install resolved     main: 'error.js',
163 silly install resolved     scripts: { test: 'make test' },
163 silly install resolved     engines: [ 'node >=0.6.0' ],
163 silly install resolved     config: { blanket: [Object], 'travis-cov': [Object] },
163 silly install resolved     author: { name: 'Jesse Proulx', email: 'github@jproulx.net' },
163 silly install resolved     license: 'ISC',
163 silly install resolved     devDependencies:
163 silly install resolved      { mocha: '',
163 silly install resolved        should: '',
163 silly install resolved        blanket: '',
163 silly install resolved        'mocha-lcov-reporter': '',
163 silly install resolved        jshint: '',
163 silly install resolved        'travis-cov': '',
163 silly install resolved        'codeclimate-test-reporter': '',
163 silly install resolved        coveralls: '' },
163 silly install resolved     repository:
163 silly install resolved      { type: 'git',
163 silly install resolved        url: 'https://github.com/jproulx/node-custom-error.git' },
163 silly install resolved     keywords: [ 'error', 'errors', 'error factory', 'custom error' ],
163 silly install resolved     bugs: { url: 'https://github.com/jproulx/node-custom-error/issues' },
163 silly install resolved     homepage: 'https://github.com/jproulx/node-custom-error',
163 silly install resolved     _id: 'custom-error-generator@7.0.0',
163 silly install resolved     dist:
163 silly install resolved      { shasum: 'b16f8d09636327f69ae80a1043766f30f4506408',
163 silly install resolved        tarball: 'http://registry.npmjs.org/custom-error-generator/-/custom-error-generator-7.0.0.tgz' },
163 silly install resolved     _from: 'custom-error-generator@7.0.0',
163 silly install resolved     _npmVersion: '1.4.3',
163 silly install resolved     _npmUser: { name: 'jproulx', email: 'github@jproulx.net' },
163 silly install resolved     maintainers: [ [Object] ],
163 silly install resolved     directories: {},
163 silly install resolved     _shasum: 'b16f8d09636327f69ae80a1043766f30f4506408',
163 silly install resolved     _resolved: 'https://registry.npmjs.org/custom-error-generator/-/custom-error-generator-7.0.0.tgz',
163 silly install resolved     readme: 'ERROR: No README data found!' } ]
164 info install custom-error-generator@7.0.0 into /Users/kengz/Google Drive/Quiver/node_modules/blpapi
165 info installOne custom-error-generator@7.0.0
166 verbose installOne of custom-error-generator to /Users/kengz/Google Drive/Quiver/node_modules/blpapi not in flight; installing
167 verbose lock using /Users/kengz/.npm/_locks/custom-error-generator-8c7673ecf0ada297.lock for /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
168 silly install write writing custom-error-generator 7.0.0 to /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
169 silly cache addNamed cb custom-error-generator@7.0.0
170 verbose unbuild node_modules/blpapi/node_modules/custom-error-generator
171 verbose gentlyRm vacuuming /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
172 verbose tar unpack /Users/kengz/.npm/custom-error-generator/7.0.0/package.tgz
173 verbose tar unpacking to /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
174 verbose gentlyRm vacuuming /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
175 silly gunzTarPerm modes [ '755', '644' ]
176 silly gunzTarPerm extractEntry package.json
177 silly gunzTarPerm extractEntry .npmignore
178 silly gunzTarPerm extractEntry README.md
179 silly gunzTarPerm extractEntry error.js
180 silly gunzTarPerm extractEntry test.js
181 silly gunzTarPerm extractEntry .jshintrc
182 silly gunzTarPerm extractEntry .travis.yml
183 silly gunzTarPerm extractEntry Makefile
184 info preinstall custom-error-generator@7.0.0
185 silly install resolved []
186 verbose about to build /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
187 info build /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
188 verbose linkStuff [ false,
188 verbose linkStuff   false,
188 verbose linkStuff   false,
188 verbose linkStuff   '/Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules' ]
189 info linkStuff custom-error-generator@7.0.0
190 verbose linkBins custom-error-generator@7.0.0
191 verbose linkMans custom-error-generator@7.0.0
192 verbose rebuildBundles custom-error-generator@7.0.0
193 info install custom-error-generator@7.0.0
194 info postinstall custom-error-generator@7.0.0
195 verbose unlock done using /Users/kengz/.npm/_locks/custom-error-generator-8c7673ecf0ada297.lock for /Users/kengz/Google Drive/Quiver/node_modules/blpapi/node_modules/custom-error-generator
196 verbose about to build /Users/kengz/Google Drive/Quiver/node_modules/blpapi
197 info build /Users/kengz/Google Drive/Quiver/node_modules/blpapi
198 verbose linkStuff [ false,
198 verbose linkStuff   false,
198 verbose linkStuff   false,
198 verbose linkStuff   '/Users/kengz/Google Drive/Quiver/node_modules' ]
199 info linkStuff blpapi@1.2.0
200 verbose linkBins blpapi@1.2.0
201 verbose linkMans blpapi@1.2.0
202 verbose rebuildBundles blpapi@1.2.0
203 verbose rebuildBundles [ 'custom-error-generator' ]
204 info install blpapi@1.2.0
205 verbose unsafe-perm in lifecycle true
206 info blpapi@1.2.0 Failed to exec install script
207 verbose unlock done using /Users/kengz/.npm/_locks/blpapi-87077b44487570ec.lock for /Users/kengz/Google Drive/Quiver/node_modules/blpapi
208 verbose stack Error: blpapi@1.2.0 install: `node-gyp configure build`
208 verbose stack Exit status 1
208 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
208 verbose stack     at EventEmitter.emit (events.js:110:17)
208 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
208 verbose stack     at ChildProcess.emit (events.js:110:17)
208 verbose stack     at maybeClose (child_process.js:1008:16)
208 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
209 verbose pkgid blpapi@1.2.0
210 verbose cwd /Users/kengz/Google Drive/Quiver
211 error Darwin 14.3.0
212 error argv "node" "/usr/local/bin/npm" "install" "blpapi"
213 error node v0.12.0
214 error npm  v2.5.1
215 error code ELIFECYCLE
216 error blpapi@1.2.0 install: `node-gyp configure build`
216 error Exit status 1
217 error Failed at the blpapi@1.2.0 install script 'node-gyp configure build'.
217 error This is most likely a problem with the blpapi package,
217 error not with npm itself.
217 error Tell the author that this fails on your system:
217 error     node-gyp configure build
217 error You can get their info via:
217 error     npm owner ls blpapi
217 error There is likely additional logging output above.
218 verbose exit [ 1, true ]
219 verbose unbuild node_modules/blpapi
220 info preuninstall blpapi@1.2.0
221 info uninstall blpapi@1.2.0
222 verbose unbuild rmStuff blpapi@1.2.0 from /Users/kengz/Google Drive/Quiver/node_modules
223 info postuninstall blpapi@1.2.0
224 verbose gentlyRm vacuuming /Users/kengz/Google Drive/Quiver/node_modules/blpapi
225 silly gentlyRm purging /Users/kengz/Google Drive/Quiver/node_modules/blpapi
226 silly gentlyRm quitting because other entries in /Users/kengz/Google Drive/Quiver/node_modules
 ```

**Comment by fabiooshiro** [comment]
I have the same issue. Is this project alive?
