### ISSUE TITLE
Windows 8 x64 module errors

### ISSUE THREAD

**Issue by IvanMMM** [bloomberg/blpapi-node#67]
Compiling with VS Pro 2013. NodeJS x64 v 0.12.4
x64 version:

```
f:\NodeJS\BLPAPI>node app.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
f:\NodeJS\BLPAPI\node_modules\blpapi\build\Release\blpapijs.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (f:\NodeJS\BLPAPI\node_modules\blpapi\blpapi.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

x32 version (set npm_config_arch="ia32"):

```
f:\NodeJS\BLPAPI>node app.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
f:\NodeJS\BLPAPI\node_modules\blpapi\build\Release\blpapijs.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (f:\NodeJS\BLPAPI\node_modules\blpapi\blpapi.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by ericvw** [comment]
@IvanMMM, can you try the latest code on `master`?  I believe #58 will address this issue - we just haven't released it yet.

**Comment by IvanMMM** [comment]
@ericvw, master branch from git works great. Thank you.
