### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by aamaritei** [bloomberg/blpapi-node#69]
Works beautifully for days, then suddenly crashes under the below error. I can't get rid of it without a system (W2003 server) restart. 

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: A dynamic link library (DLL) initialization routine failed.

D:\BLB\node_modules\blpapi\build\Release\blpapijs.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\BLB\node_modules\blpapi\blpapi.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by ericvw** [comment]
@norphe, it appears this is during initialization; is that correct?  Most likely these DLL load errors are due to improper library search paths with the host machine, not `blpapi-node` itself.
