### ISSUE TITLE
Specified module could not be found, when running examples

### ISSUE THREAD

**Issue by Bondifrench** [bloomberg/blpapi-node#78]
when trying both `node FieldSearchRequest.js` or `node HistoricalDataRequest.js` I get the following error:
````
$ node FieldSearchRequest.js
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\c:\Users\London\Apps\financejs\node_modules\blpapi\build\Release\blpapijs.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\London\Apps\financejs\node_modules\blpapi\blpapi.js:4:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
````
Any advice?
I have `node v6.9.2` and `npm v4.0.5` on a Windows 8.1 PC with BBG terminal logged in on the same machine.

**Comment by Bondifrench** [comment]
So I did a bit of research and from this [thread](https://github.com/soldair/node-qrcode/issues/22) I used a software called [dependencywalker](http://dependencywalker.com/) to look for what would be causing the error.
I got this:
![image](https://cloud.githubusercontent.com/assets/4905917/21181116/6dc05dce-c250-11e6-8b09-44dfa619a138.png)

So the first missing `.dll` module `BLPAPI3_64.DLL` I recognised, I saw it in [here](https://github.com/bloomberg/blpapi-node/tree/master/deps/blpapi/win).
However for some reason, it seems when installing `blpapi` the `dll` files are not copied there:
![image](https://cloud.githubusercontent.com/assets/4905917/21181437/04d4cac8-c252-11e6-946b-d707ac0c5117.png)
so when `node-gyp configure build` happens it doesn't put `BLPAPI3_64.DLL` in the right place (C:\Users\London\Apps\financejs\node_modules\blpapi\build), so I did manually.

After rebuilding `blpapi` it got rid of the previous problem but then: 
![image](https://cloud.githubusercontent.com/assets/4905917/21182173/d3c812c4-c255-11e6-9468-b8236d744989.png)

When trying to run the examples, I still got some errors, as `BLPAPI3_64.DLL` was only the first items in the list of DLLs that `dependencywalker` identified as missing.
@apaprocki @ericvw Any ideas?

**Comment by apaprocki** [comment]
Windows is tricky because there are a few variables. What version of MSVC do you have installed? If you run `cl.exe` from its binary directory, what is the exact version string reported?

**Comment by Bondifrench** [comment]
So I have `Microsoft Visual Studio 14` and the string reported with `cl.exe` says:
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

**Comment by Bondifrench** [comment]
OK, finally managed to run the examples without errors!!
Although I had BBG running on my machine and logged in there...I had to launch explicitly `BBComm` in the background for the examples to run and be able to connect to port `8194` otherwise I get the tcp connection failed mentioned in previous screens.

Might be nice to put a mention in the docs.
